### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by pandusonu2** [NIT-dgp/UIP#19]
Traceback (most recent call last):
  File "UIP.py", line 4, in <module>
    scheduler()
  File "/home/sonu/UIP/scheduler.py", line 10, in __init__
    self.initFetch()
  File "/home/sonu/UIP/scheduler.py", line 17, in initFetch
    get_images(WEBSITE)
  File "/home/sonu/UIP/scrape.py", line 49, in get_images
    urlretrieve(image,os.path.join(path,filename),reporthook=dlProgress)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by abhsag24** [comment]
pushing a hotfix, happens due to two reasons:
1. Too many requests, reddit only allows 60 requests per minute
2. some links are bad.

I can correct the 2nd case by using a try and except block at the time of retrieving a url, in `scrape.py`  but we'll have to use an official account and use `OAuth2` to get by 1.

**Comment by abhsag24** [comment]
Closes with https://github.com/NIT-dgp/UIP/commit/00c06916d910ac6ba39f1b8488b0672f5049a6a1 , forgot to add the the issue in commit :P
