### ISSUE TITLE
GUI: Download Button (downloadBtn) not defined

### ISSUE THREAD

**Issue by Aniq55** [NIT-dgp/UIP#284]
```
Traceback (most recent call last):
  File "/usr/local/bin/UIP", line 11, in <module>
    load_entry_point('UIP==0.0.3', 'console_scripts', 'UIP')()
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/UIP.py", line 61, in main
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/gui/mainGui.py", line 29, in __init__
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/gui/mainGui.py", line 36, in create_ui
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/gui/generalTab.py", line 40, in create_general_tab
NameError: name 'downloadBtn' is not defined
```

**Comment by abhsag24** [comment]
why close this the PR is not merged
