### ISSUE TITLE
Error: When adding wallpaper as favourite 

### ISSUE THREAD

**Issue by yasethiya** [NIT-dgp/UIP#346]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.5/dist-packages/UIP-0.0.3-py3.5.egg/uiplib/gui/mainGui.py", line 133, in favourite
    copy(self.images[self.index], self.settings['fav-pics-folder'])
  File "/usr/lib/python3.5/shutil.py", line 234, in copy
    dst = os.path.join(dst, os.path.basename(src))
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'UipImage' object has no attribute 'rfind'
```

**Comment by yasethiya** [comment]
no file is showing named shutil.py and posixpath.py in python3.5 directory,how this is possible where i am going wrong?

**Comment by abhsag24** [comment]
these are standard libraries in python , the thing is shutil needs `image_path` while `images` is a list of `uipImages` just do ` copy(self.images[self.index],image_path, self.settings['fav-pics-folder'])` instead of the earlier line in `favorite` function

**Comment by SACHIN-13** [comment]
Added a PR #349 . plz check!
